/**
 * Google Places API (New) Table A types — allowed for searchNearby includedTypes.
 * Source: https://developers.google.com/maps/documentation/places/web-service/place-types
 * Keys are the Google type ids; labels are UI-facing.
 */

export type PlaceTypeStrategy =
  | { kind: 'nearby'; includedTypes: string[] }
  | { kind: 'text'; textQuery: string };

export type PlaceTypeEntry = {
  label: string;
  category: string;
  strategy: PlaceTypeStrategy;
};

/** Grouped Table A types for Nearest-column pickers (optgroups). */
export const PLACE_TYPE_GROUPS: ReadonlyArray<{
  category: string;
  types: ReadonlyArray<{ key: string; label: string }>;
}> = [
  {
    category: "Automotive",
    types: [
      { key: "car_dealer", label: "Car Dealer" },
      { key: "car_rental", label: "Car Rental" },
      { key: "car_repair", label: "Car Repair" },
      { key: "car_wash", label: "Car Wash" },
      { key: "ebike_charging_station", label: "E-bike charging station" },
      { key: "electric_vehicle_charging_station", label: "Electric Vehicle Charging Station" },
      { key: "gas_station", label: "Gas Station" },
      { key: "parking", label: "Parking" },
      { key: "parking_garage", label: "Parking Garage" },
      { key: "parking_lot", label: "Parking Lot" },
      { key: "rest_stop", label: "Rest Stop" },
      { key: "tire_shop", label: "Tire Shop" },
      { key: "truck_dealer", label: "Truck Dealer" },
    ],
  },
  {
    category: "Business",
    types: [
      { key: "business_center", label: "Business Center" },
      { key: "corporate_office", label: "Corporate Office" },
      { key: "coworking_space", label: "Coworking Space" },
      { key: "farm", label: "Farm" },
      { key: "manufacturer", label: "Manufacturer" },
      { key: "ranch", label: "Ranch" },
      { key: "supplier", label: "Supplier" },
      { key: "television_studio", label: "Television Studio" },
    ],
  },
  {
    category: "Culture",
    types: [
      { key: "art_gallery", label: "Art Gallery" },
      { key: "art_museum", label: "Art Museum" },
      { key: "art_studio", label: "Art Studio" },
      { key: "auditorium", label: "Auditorium" },
      { key: "castle", label: "Castle" },
      { key: "cultural_landmark", label: "Cultural Landmark" },
      { key: "fountain", label: "Fountain" },
      { key: "historical_place", label: "Historical Place" },
      { key: "history_museum", label: "History Museum" },
      { key: "monument", label: "Monument" },
      { key: "museum", label: "Museum" },
      { key: "performing_arts_theater", label: "Performing Arts Theater" },
      { key: "sculpture", label: "Sculpture" },
    ],
  },
  {
    category: "Education",
    types: [
      { key: "academic_department", label: "Academic Department" },
      { key: "educational_institution", label: "Educational Institution" },
      { key: "library", label: "Library" },
      { key: "preschool", label: "Preschool" },
      { key: "primary_school", label: "Primary School" },
      { key: "research_institute", label: "Research Institute" },
      { key: "school", label: "School" },
      { key: "secondary_school", label: "Secondary School" },
      { key: "university", label: "University" },
    ],
  },
  {
    category: "Entertainment and Recreation",
    types: [
      { key: "adventure_sports_center", label: "Adventure Sports Center" },
      { key: "amphitheatre", label: "Amphitheatre" },
      { key: "amusement_center", label: "Amusement Center" },
      { key: "amusement_park", label: "Amusement Park" },
      { key: "aquarium", label: "Aquarium" },
      { key: "banquet_hall", label: "Banquet Hall" },
      { key: "barbecue_area", label: "Barbecue Area" },
      { key: "botanical_garden", label: "Botanical Garden" },
      { key: "bowling_alley", label: "Bowling Alley" },
      { key: "casino", label: "Casino" },
      { key: "childrens_camp", label: "Childrens Camp" },
      { key: "city_park", label: "City Park" },
      { key: "comedy_club", label: "Comedy Club" },
      { key: "community_center", label: "Community Center" },
      { key: "concert_hall", label: "Concert Hall" },
      { key: "convention_center", label: "Convention Center" },
      { key: "cultural_center", label: "Cultural Center" },
      { key: "cycling_park", label: "Cycling Park" },
      { key: "dance_hall", label: "Dance Hall" },
      { key: "dog_park", label: "Dog Park" },
      { key: "event_venue", label: "Event Venue" },
      { key: "ferris_wheel", label: "Ferris Wheel" },
      { key: "garden", label: "Garden" },
      { key: "go_karting_venue", label: "Go Karting Venue" },
      { key: "hiking_area", label: "Hiking Area" },
      { key: "historical_landmark", label: "Historical Landmark" },
      { key: "indoor_playground", label: "Indoor Playground" },
      { key: "internet_cafe", label: "Internet Cafe" },
      { key: "karaoke", label: "Karaoke" },
      { key: "live_music_venue", label: "Live Music Venue" },
      { key: "marina", label: "Marina" },
      { key: "miniature_golf_course", label: "Miniature Golf Course" },
      { key: "movie_rental", label: "Movie Rental" },
      { key: "movie_theater", label: "Movie Theater" },
      { key: "national_park", label: "National Park" },
      { key: "night_club", label: "Night Club" },
      { key: "observation_deck", label: "Observation Deck" },
      { key: "off_roading_area", label: "Off Roading Area" },
      { key: "opera_house", label: "Opera House" },
      { key: "paintball_center", label: "Paintball Center" },
      { key: "park", label: "Park" },
      { key: "philharmonic_hall", label: "Philharmonic Hall" },
      { key: "picnic_ground", label: "Picnic Ground" },
      { key: "planetarium", label: "Planetarium" },
      { key: "plaza", label: "Plaza" },
      { key: "roller_coaster", label: "Roller Coaster" },
      { key: "skateboard_park", label: "Skateboard Park" },
      { key: "state_park", label: "State Park" },
      { key: "tourist_attraction", label: "Tourist Attraction" },
      { key: "video_arcade", label: "Video Arcade" },
      { key: "vineyard", label: "Vineyard" },
      { key: "visitor_center", label: "Visitor Center" },
      { key: "water_park", label: "Water Park" },
      { key: "wedding_venue", label: "Wedding Venue" },
      { key: "wildlife_park", label: "Wildlife Park" },
      { key: "wildlife_refuge", label: "Wildlife Refuge" },
      { key: "zoo", label: "Zoo" },
    ],
  },
  {
    category: "Facilities",
    types: [
      { key: "public_bath", label: "Public Bath" },
      { key: "public_bathroom", label: "Public Bathroom" },
      { key: "stable", label: "Stable" },
    ],
  },
  {
    category: "Finance",
    types: [
      { key: "accounting", label: "Accounting" },
      { key: "atm", label: "ATM" },
      { key: "bank", label: "Bank" },
    ],
  },
  {
    category: "Food and Drink",
    types: [
      { key: "acai_shop", label: "Acai Shop" },
      { key: "afghani_restaurant", label: "Afghani Restaurant" },
      { key: "african_restaurant", label: "African Restaurant" },
      { key: "american_restaurant", label: "American Restaurant" },
      { key: "argentinian_restaurant", label: "Argentinian Restaurant" },
      { key: "asian_fusion_restaurant", label: "Asian Fusion Restaurant" },
      { key: "asian_restaurant", label: "Asian Restaurant" },
      { key: "australian_restaurant", label: "Australian Restaurant" },
      { key: "austrian_restaurant", label: "Austrian Restaurant" },
      { key: "bagel_shop", label: "Bagel Shop" },
      { key: "bakery", label: "Bakery" },
      { key: "bangladeshi_restaurant", label: "Bangladeshi Restaurant" },
      { key: "bar", label: "Bar" },
      { key: "bar_and_grill", label: "Bar And Grill" },
      { key: "barbecue_restaurant", label: "Barbecue Restaurant" },
      { key: "basque_restaurant", label: "Basque Restaurant" },
      { key: "bavarian_restaurant", label: "Bavarian Restaurant" },
      { key: "beer_garden", label: "Beer Garden" },
      { key: "belgian_restaurant", label: "Belgian Restaurant" },
      { key: "bistro", label: "Bistro" },
      { key: "brazilian_restaurant", label: "Brazilian Restaurant" },
      { key: "breakfast_restaurant", label: "Breakfast Restaurant" },
      { key: "brewery", label: "Brewery" },
      { key: "brewpub", label: "Brewpub" },
      { key: "british_restaurant", label: "British Restaurant" },
      { key: "brunch_restaurant", label: "Brunch Restaurant" },
      { key: "buffet_restaurant", label: "Buffet Restaurant" },
      { key: "burmese_restaurant", label: "Burmese Restaurant" },
      { key: "burrito_restaurant", label: "Burrito Restaurant" },
      { key: "cafe", label: "Cafe" },
      { key: "cafeteria", label: "Cafeteria" },
      { key: "cajun_restaurant", label: "Cajun Restaurant" },
      { key: "cake_shop", label: "Cake Shop" },
      { key: "californian_restaurant", label: "Californian Restaurant" },
      { key: "cambodian_restaurant", label: "Cambodian Restaurant" },
      { key: "candy_store", label: "Candy Store" },
      { key: "cantonese_restaurant", label: "Cantonese Restaurant" },
      { key: "caribbean_restaurant", label: "Caribbean Restaurant" },
      { key: "cat_cafe", label: "Cat Cafe" },
      { key: "chicken_restaurant", label: "Chicken Restaurant" },
      { key: "chicken_wings_restaurant", label: "Chicken Wings Restaurant" },
      { key: "chilean_restaurant", label: "Chilean Restaurant" },
      { key: "chinese_noodle_restaurant", label: "Chinese Noodle Restaurant" },
      { key: "chinese_restaurant", label: "Chinese Restaurant" },
      { key: "chocolate_factory", label: "Chocolate Factory" },
      { key: "chocolate_shop", label: "Chocolate Shop" },
      { key: "cocktail_bar", label: "Cocktail Bar" },
      { key: "coffee_roastery", label: "Coffee Roastery" },
      { key: "coffee_shop", label: "Coffee Shop" },
      { key: "coffee_stand", label: "Coffee Stand" },
      { key: "colombian_restaurant", label: "Colombian Restaurant" },
      { key: "confectionery", label: "Confectionery" },
      { key: "croatian_restaurant", label: "Croatian Restaurant" },
      { key: "cuban_restaurant", label: "Cuban Restaurant" },
      { key: "czech_restaurant", label: "Czech Restaurant" },
      { key: "danish_restaurant", label: "Danish Restaurant" },
      { key: "deli", label: "Deli" },
      { key: "dessert_restaurant", label: "Dessert Restaurant" },
      { key: "dessert_shop", label: "Dessert Shop" },
      { key: "dim_sum_restaurant", label: "Dim Sum Restaurant" },
      { key: "diner", label: "Diner" },
      { key: "dog_cafe", label: "Dog Cafe" },
      { key: "donut_shop", label: "Donut Shop" },
      { key: "dumpling_restaurant", label: "Dumpling Restaurant" },
      { key: "dutch_restaurant", label: "Dutch Restaurant" },
      { key: "eastern_european_restaurant", label: "Eastern European Restaurant" },
      { key: "ethiopian_restaurant", label: "Ethiopian Restaurant" },
      { key: "european_restaurant", label: "European Restaurant" },
      { key: "falafel_restaurant", label: "Falafel Restaurant" },
      { key: "family_restaurant", label: "Family Restaurant" },
      { key: "fast_food_restaurant", label: "Fast Food Restaurant" },
      { key: "filipino_restaurant", label: "Filipino Restaurant" },
      { key: "fine_dining_restaurant", label: "Fine Dining Restaurant" },
      { key: "fish_and_chips_restaurant", label: "Fish And Chips Restaurant" },
      { key: "fondue_restaurant", label: "Fondue Restaurant" },
      { key: "food_court", label: "Food Court" },
      { key: "french_restaurant", label: "French Restaurant" },
      { key: "fusion_restaurant", label: "Fusion Restaurant" },
      { key: "gastropub", label: "Gastropub" },
      { key: "german_restaurant", label: "German Restaurant" },
      { key: "greek_restaurant", label: "Greek Restaurant" },
      { key: "gyro_restaurant", label: "Gyro Restaurant" },
      { key: "halal_restaurant", label: "Halal Restaurant" },
      { key: "hamburger_restaurant", label: "Hamburger Restaurant" },
      { key: "hawaiian_restaurant", label: "Hawaiian Restaurant" },
      { key: "hookah_bar", label: "Hookah Bar" },
      { key: "hot_dog_restaurant", label: "Hot Dog Restaurant" },
      { key: "hot_dog_stand", label: "Hot Dog Stand" },
      { key: "hot_pot_restaurant", label: "Hot Pot Restaurant" },
      { key: "hungarian_restaurant", label: "Hungarian Restaurant" },
      { key: "ice_cream_shop", label: "Ice Cream Shop" },
      { key: "indian_restaurant", label: "Indian Restaurant" },
      { key: "indonesian_restaurant", label: "Indonesian Restaurant" },
      { key: "irish_pub", label: "Irish Pub" },
      { key: "irish_restaurant", label: "Irish Restaurant" },
      { key: "israeli_restaurant", label: "Israeli Restaurant" },
      { key: "italian_restaurant", label: "Italian Restaurant" },
      { key: "japanese_curry_restaurant", label: "Japanese Curry Restaurant" },
      { key: "japanese_izakaya_restaurant", label: "Japanese Izakaya Restaurant" },
      { key: "japanese_restaurant", label: "Japanese Restaurant" },
      { key: "juice_shop", label: "Juice Shop" },
      { key: "kebab_shop", label: "Kebab Shop" },
      { key: "korean_barbecue_restaurant", label: "Korean Barbecue Restaurant" },
      { key: "korean_restaurant", label: "Korean Restaurant" },
      { key: "latin_american_restaurant", label: "Latin American Restaurant" },
      { key: "lebanese_restaurant", label: "Lebanese Restaurant" },
      { key: "lounge_bar", label: "Lounge Bar" },
      { key: "malaysian_restaurant", label: "Malaysian Restaurant" },
      { key: "meal_delivery", label: "Meal Delivery" },
      { key: "meal_takeaway", label: "Meal Takeaway" },
      { key: "mediterranean_restaurant", label: "Mediterranean Restaurant" },
      { key: "mexican_restaurant", label: "Mexican Restaurant" },
      { key: "middle_eastern_restaurant", label: "Middle Eastern Restaurant" },
      { key: "mongolian_barbecue_restaurant", label: "Mongolian Barbecue Restaurant" },
      { key: "moroccan_restaurant", label: "Moroccan Restaurant" },
      { key: "noodle_shop", label: "Noodle Shop" },
      { key: "north_indian_restaurant", label: "North Indian Restaurant" },
      { key: "oyster_bar_restaurant", label: "Oyster Bar Restaurant" },
      { key: "pakistani_restaurant", label: "Pakistani Restaurant" },
      { key: "pastry_shop", label: "Pastry Shop" },
      { key: "persian_restaurant", label: "Persian Restaurant" },
      { key: "peruvian_restaurant", label: "Peruvian Restaurant" },
      { key: "pizza_delivery", label: "Pizza Delivery" },
      { key: "pizza_restaurant", label: "Pizza Restaurant" },
      { key: "polish_restaurant", label: "Polish Restaurant" },
      { key: "portuguese_restaurant", label: "Portuguese Restaurant" },
      { key: "pub", label: "Pub" },
      { key: "ramen_restaurant", label: "Ramen Restaurant" },
      { key: "restaurant", label: "Restaurant" },
      { key: "romanian_restaurant", label: "Romanian Restaurant" },
      { key: "russian_restaurant", label: "Russian Restaurant" },
      { key: "salad_shop", label: "Salad Shop" },
      { key: "sandwich_shop", label: "Sandwich Shop" },
      { key: "scandinavian_restaurant", label: "Scandinavian Restaurant" },
      { key: "seafood_restaurant", label: "Seafood Restaurant" },
      { key: "shawarma_restaurant", label: "Shawarma Restaurant" },
      { key: "snack_bar", label: "Snack Bar" },
      { key: "soul_food_restaurant", label: "Soul Food Restaurant" },
      { key: "soup_restaurant", label: "Soup Restaurant" },
      { key: "south_american_restaurant", label: "South American Restaurant" },
      { key: "south_indian_restaurant", label: "South Indian Restaurant" },
      { key: "southwestern_us_restaurant", label: "Southwestern US Restaurant" },
      { key: "spanish_restaurant", label: "Spanish Restaurant" },
      { key: "sports_bar", label: "Sports Bar" },
      { key: "sri_lankan_restaurant", label: "Sri Lankan Restaurant" },
      { key: "steak_house", label: "Steak House" },
      { key: "sushi_restaurant", label: "Sushi Restaurant" },
      { key: "swiss_restaurant", label: "Swiss Restaurant" },
      { key: "taco_restaurant", label: "Taco Restaurant" },
      { key: "taiwanese_restaurant", label: "Taiwanese Restaurant" },
      { key: "tapas_restaurant", label: "Tapas Restaurant" },
      { key: "tea_house", label: "Tea House" },
      { key: "tex_mex_restaurant", label: "Tex Mex Restaurant" },
      { key: "thai_restaurant", label: "Thai Restaurant" },
      { key: "tibetan_restaurant", label: "Tibetan Restaurant" },
      { key: "tonkatsu_restaurant", label: "Tonkatsu Restaurant" },
      { key: "turkish_restaurant", label: "Turkish Restaurant" },
      { key: "ukrainian_restaurant", label: "Ukrainian Restaurant" },
      { key: "vegan_restaurant", label: "Vegan Restaurant" },
      { key: "vegetarian_restaurant", label: "Vegetarian Restaurant" },
      { key: "vietnamese_restaurant", label: "Vietnamese Restaurant" },
      { key: "western_restaurant", label: "Western Restaurant" },
      { key: "wine_bar", label: "Wine Bar" },
      { key: "winery", label: "Winery" },
      { key: "yakiniku_restaurant", label: "Yakiniku Restaurant" },
      { key: "yakitori_restaurant", label: "Yakitori Restaurant" },
    ],
  },
  {
    category: "Geographical Areas",
    types: [
      { key: "administrative_area_level_1", label: "Administrative Area Level 1" },
      { key: "administrative_area_level_2", label: "Administrative Area Level 2" },
      { key: "country", label: "Country" },
      { key: "locality", label: "Locality" },
      { key: "postal_code", label: "Postal Code" },
      { key: "school_district", label: "School District" },
    ],
  },
  {
    category: "Government",
    types: [
      { key: "city_hall", label: "City Hall" },
      { key: "courthouse", label: "Courthouse" },
      { key: "embassy", label: "Embassy" },
      { key: "fire_station", label: "Fire Station" },
      { key: "government_office", label: "Government Office" },
      { key: "local_government_office", label: "Local Government Office" },
      { key: "neighborhood_police_station", label: "Neighborhood Police Station" },
      { key: "police", label: "Police" },
      { key: "post_office", label: "Post Office" },
    ],
  },
  {
    category: "Health and Wellness",
    types: [
      { key: "chiropractor", label: "Chiropractor" },
      { key: "dental_clinic", label: "Dental Clinic" },
      { key: "dentist", label: "Dentist" },
      { key: "doctor", label: "Doctor" },
      { key: "drugstore", label: "Drugstore" },
      { key: "general_hospital", label: "General Hospital" },
      { key: "hospital", label: "Hospital" },
      { key: "massage", label: "Massage" },
      { key: "massage_spa", label: "Massage Spa" },
      { key: "medical_center", label: "Medical Center" },
      { key: "medical_clinic", label: "Medical Clinic" },
      { key: "medical_lab", label: "Medical Lab" },
      { key: "pharmacy", label: "Pharmacy" },
      { key: "physiotherapist", label: "Physiotherapist" },
      { key: "sauna", label: "Sauna" },
      { key: "skin_care_clinic", label: "Skin Care Clinic" },
      { key: "spa", label: "Spa" },
      { key: "tanning_studio", label: "Tanning Studio" },
      { key: "wellness_center", label: "Wellness Center" },
      { key: "yoga_studio", label: "Yoga Studio" },
    ],
  },
  {
    category: "Housing",
    types: [
      { key: "apartment_building", label: "Apartment Building" },
      { key: "apartment_complex", label: "Apartment Complex" },
      { key: "condominium_complex", label: "Condominium Complex" },
      { key: "housing_complex", label: "Housing Complex" },
    ],
  },
  {
    category: "Lodging",
    types: [
      { key: "bed_and_breakfast", label: "Bed And Breakfast" },
      { key: "budget_japanese_inn", label: "Budget Japanese Inn" },
      { key: "campground", label: "Campground" },
      { key: "camping_cabin", label: "Camping Cabin" },
      { key: "cottage", label: "Cottage" },
      { key: "extended_stay_hotel", label: "Extended Stay Hotel" },
      { key: "farmstay", label: "Farmstay" },
      { key: "guest_house", label: "Guest House" },
      { key: "hostel", label: "Hostel" },
      { key: "hotel", label: "Hotel" },
      { key: "inn", label: "Inn" },
      { key: "japanese_inn", label: "Japanese Inn" },
      { key: "lodging", label: "Lodging" },
      { key: "mobile_home_park", label: "Mobile Home Park" },
      { key: "motel", label: "Motel" },
      { key: "private_guest_room", label: "Private Guest Room" },
      { key: "resort_hotel", label: "Resort Hotel" },
      { key: "rv_park", label: "Rv Park" },
    ],
  },
  {
    category: "Natural Features",
    types: [
      { key: "beach", label: "Beach" },
      { key: "island", label: "Island" },
      { key: "lake", label: "Lake" },
      { key: "mountain_peak", label: "Mountain Peak" },
      { key: "nature_preserve", label: "Nature Preserve" },
      { key: "river", label: "River" },
      { key: "scenic_spot", label: "Scenic Spot" },
      { key: "woods", label: "Woods" },
    ],
  },
  {
    category: "Places of Worship",
    types: [
      { key: "buddhist_temple", label: "Buddhist Temple" },
      { key: "church", label: "Church" },
      { key: "hindu_temple", label: "Hindu Temple" },
      { key: "mosque", label: "Mosque" },
      { key: "shinto_shrine", label: "Shinto Shrine" },
      { key: "synagogue", label: "Synagogue" },
    ],
  },
  {
    category: "Services",
    types: [
      { key: "aircraft_rental_service", label: "Aircraft Rental Service" },
      { key: "association_or_organization", label: "Association Or Organization" },
      { key: "astrologer", label: "Astrologer" },
      { key: "barber_shop", label: "Barber Shop" },
      { key: "beautician", label: "Beautician" },
      { key: "beauty_salon", label: "Beauty Salon" },
      { key: "body_art_service", label: "Body Art Service" },
      { key: "catering_service", label: "Catering Service" },
      { key: "cemetery", label: "Cemetery" },
      { key: "chauffeur_service", label: "Chauffeur Service" },
      { key: "child_care_agency", label: "Child Care Agency" },
      { key: "consultant", label: "Consultant" },
      { key: "courier_service", label: "Courier Service" },
      { key: "electrician", label: "Electrician" },
      { key: "employment_agency", label: "Employment Agency" },
      { key: "florist", label: "Florist" },
      { key: "food_delivery", label: "Food Delivery" },
      { key: "foot_care", label: "Foot Care" },
      { key: "funeral_home", label: "Funeral Home" },
      { key: "hair_care", label: "Hair Care" },
      { key: "hair_salon", label: "Hair Salon" },
      { key: "insurance_agency", label: "Insurance Agency" },
      { key: "laundry", label: "Laundry" },
      { key: "lawyer", label: "Lawyer" },
      { key: "locksmith", label: "Locksmith" },
      { key: "makeup_artist", label: "Makeup Artist" },
      { key: "marketing_consultant", label: "Marketing Consultant" },
      { key: "moving_company", label: "Moving Company" },
      { key: "nail_salon", label: "Nail Salon" },
      { key: "non_profit_organization", label: "Non Profit Organization" },
      { key: "painter", label: "Painter" },
      { key: "pet_boarding_service", label: "Pet Boarding Service" },
      { key: "pet_care", label: "Pet Care" },
      { key: "plumber", label: "Plumber" },
      { key: "psychic", label: "Psychic" },
      { key: "real_estate_agency", label: "Real Estate Agency" },
      { key: "roofing_contractor", label: "Roofing Contractor" },
      { key: "service", label: "Service" },
      { key: "shipping_service", label: "Shipping Service" },
      { key: "storage", label: "Storage" },
      { key: "summer_camp_organizer", label: "Summer Camp Organizer" },
      { key: "tailor", label: "Tailor" },
      { key: "telecommunications_service_provider", label: "Telecommunications Service Provider" },
      { key: "tour_agency", label: "Tour Agency" },
      { key: "tourist_information_center", label: "Tourist Information Center" },
      { key: "travel_agency", label: "Travel Agency" },
      { key: "veterinary_care", label: "Veterinary Care" },
    ],
  },
  {
    category: "Shopping",
    types: [
      { key: "asian_grocery_store", label: "Asian Grocery Store" },
      { key: "auto_parts_store", label: "Auto Parts Store" },
      { key: "bicycle_store", label: "Bicycle Store" },
      { key: "book_store", label: "Book Store" },
      { key: "building_materials_store", label: "Building Materials Store" },
      { key: "butcher_shop", label: "Butcher Shop" },
      { key: "cell_phone_store", label: "Cell Phone Store" },
      { key: "clothing_store", label: "Clothing Store" },
      { key: "convenience_store", label: "Convenience Store" },
      { key: "cosmetics_store", label: "Cosmetics Store" },
      { key: "department_store", label: "Department Store" },
      { key: "discount_store", label: "Discount Store" },
      { key: "discount_supermarket", label: "Discount Supermarket" },
      { key: "electronics_store", label: "Electronics Store" },
      { key: "farmers_market", label: "Farmers Market" },
      { key: "flea_market", label: "Flea Market" },
      { key: "food_store", label: "Food Store" },
      { key: "furniture_store", label: "Furniture Store" },
      { key: "garden_center", label: "Garden Center" },
      { key: "general_store", label: "General Store" },
      { key: "gift_shop", label: "Gift Shop" },
      { key: "grocery_store", label: "Grocery Store" },
      { key: "hardware_store", label: "Hardware Store" },
      { key: "health_food_store", label: "Health Food Store" },
      { key: "home_goods_store", label: "Home Goods Store" },
      { key: "home_improvement_store", label: "Home Improvement Store" },
      { key: "hypermarket", label: "Hypermarket" },
      { key: "jewelry_store", label: "Jewelry Store" },
      { key: "liquor_store", label: "Liquor Store" },
      { key: "market", label: "Market" },
      { key: "pet_store", label: "Pet Store" },
      { key: "shoe_store", label: "Shoe Store" },
      { key: "shopping_mall", label: "Shopping Mall" },
      { key: "sporting_goods_store", label: "Sporting Goods Store" },
      { key: "sportswear_store", label: "Sportswear Store" },
      { key: "store", label: "Store" },
      { key: "supermarket", label: "Supermarket" },
      { key: "tea_store", label: "Tea Store" },
      { key: "thrift_store", label: "Thrift Store" },
      { key: "toy_store", label: "Toy Store" },
      { key: "warehouse_store", label: "Warehouse Store" },
      { key: "wholesaler", label: "Wholesaler" },
      { key: "womens_clothing_store", label: "Womens Clothing Store" },
    ],
  },
  {
    category: "Sports",
    types: [
      { key: "arena", label: "Arena" },
      { key: "athletic_field", label: "Athletic Field" },
      { key: "fishing_charter", label: "Fishing Charter" },
      { key: "fishing_pier", label: "Fishing Pier" },
      { key: "fishing_pond", label: "Fishing Pond" },
      { key: "fitness_center", label: "Fitness Center" },
      { key: "golf_course", label: "Golf Course" },
      { key: "gym", label: "Gym" },
      { key: "ice_skating_rink", label: "Ice Skating Rink" },
      { key: "indoor_golf_course", label: "Indoor Golf Course" },
      { key: "playground", label: "Playground" },
      { key: "race_course", label: "Race Course" },
      { key: "ski_resort", label: "Ski Resort" },
      { key: "sports_activity_location", label: "Sports Activity Location" },
      { key: "sports_club", label: "Sports Club" },
      { key: "sports_coaching", label: "Sports Coaching" },
      { key: "sports_complex", label: "Sports Complex" },
      { key: "sports_school", label: "Sports School" },
      { key: "stadium", label: "Stadium" },
      { key: "swimming_pool", label: "Swimming Pool" },
      { key: "tennis_court", label: "Tennis Court" },
    ],
  },
  {
    category: "Transportation",
    types: [
      { key: "airport", label: "Airport" },
      { key: "airstrip", label: "Airstrip" },
      { key: "bike_sharing_station", label: "Bike Sharing Station" },
      { key: "bridge", label: "Bridge" },
      { key: "bus_station", label: "Bus Station" },
      { key: "bus_stop", label: "Bus Stop" },
      { key: "ferry_service", label: "Ferry Service" },
      { key: "ferry_terminal", label: "Ferry Terminal" },
      { key: "heliport", label: "Heliport" },
      { key: "international_airport", label: "International Airport" },
      { key: "light_rail_station", label: "Light Rail Station" },
      { key: "park_and_ride", label: "Park And Ride" },
      { key: "subway_station", label: "Subway Station" },
      { key: "taxi_service", label: "Taxi Service" },
      { key: "taxi_stand", label: "Taxi Stand" },
      { key: "toll_station", label: "Toll Station" },
      { key: "train_station", label: "Train Station" },
      { key: "train_ticket_office", label: "Train Ticket Office" },
      { key: "tram_stop", label: "Tram Stop" },
      { key: "transit_depot", label: "Transit Depot" },
      { key: "transit_station", label: "Transit Station" },
      { key: "transit_stop", label: "Transit Stop" },
      { key: "transportation_service", label: "Transportation Service" },
      { key: "truck_stop", label: "Truck Stop" },
    ],
  },
];

function buildCatalog(): Record<string, PlaceTypeEntry> {
  const catalog: Record<string, PlaceTypeEntry> = {};
  for (const group of PLACE_TYPE_GROUPS) {
    for (const t of group.types) {
      catalog[t.key] = {
        label: t.label,
        category: group.category,
        strategy: { kind: 'nearby', includedTypes: [t.key] },
      };
    }
  }
  return catalog;
}

export const PLACE_TYPE_CATALOG: Record<string, PlaceTypeEntry> =
  buildCatalog();

/** Google Table A type id used as proximity place_type_key. */
export type PlaceTypeKey = string;

export function isPlaceTypeKey(key: string): key is PlaceTypeKey {
  return Object.prototype.hasOwnProperty.call(PLACE_TYPE_CATALOG, key);
}

export function placeTypeLabel(key: string): string {
  return PLACE_TYPE_CATALOG[key]?.label ?? key;
}

export const PROXIMITY_SHORTLIST_N = 5;

/** How many routed candidates to return for user choice (listing explore). */
export const PROXIMITY_CHOICE_N = 5;

export type PoiCandidate = {
  placeId: string;
  name: string;
  lat: number;
  lng: number;
  formattedAddress?: string;
};
